export function getLandingCSS(){return `
.landing-shell{position:relative;min-height:100svh;overflow:hidden;padding:0 24px;background:var(--s1)}
.landing-shell::before{content:'';position:absolute;inset:0;background:radial-gradient(circle at 72% 34%,rgba(111,143,114,.16),transparent 24%),radial-gradient(circle at 18% 76%,rgba(242,166,90,.045),transparent 20%);pointer-events:none}
.landing-shell::after{content:'';position:absolute;inset:0;background-image:linear-gradient(rgba(255,255,255,.022) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.022) 1px,transparent 1px);background-size:64px 64px;mask-image:linear-gradient(to bottom,transparent,black 20%,black 80%,transparent);pointer-events:none;opacity:.35}
.landing-ambient{position:absolute;right:-8%;bottom:8%;width:min(54vw,760px);aspect-ratio:1;border-radius:50%;background:radial-gradient(circle,rgba(111,143,114,.16),rgba(111,143,114,.035) 36%,transparent 70%);filter:blur(12px);transform:translate3d(var(--mx,0),var(--my,0),0);animation:land-breathe 7s ease-in-out infinite;pointer-events:none}
.landing-panel{position:relative;z-index:2;width:min(1180px,100%);min-height:100svh;margin:auto;display:grid;grid-template-columns:minmax(0,1.02fr) minmax(340px,.8fr);align-items:center;gap:clamp(48px,7vw,120px);padding:96px 0 72px}
.landing-copy-wrap{position:relative}.landing-kicker-row{display:flex;align-items:center;gap:10px;margin-bottom:24px;opacity:0;transform:translateY(14px);animation:land-in .65s .08s cubic-bezier(.2,.75,.25,1) forwards}.landing-kicker{font-size:10px;letter-spacing:.16em;font-weight:700;color:var(--t3)}
.landing-title{max-width:760px;font-size:clamp(3.4rem,7.5vw,6.8rem);line-height:.93;letter-spacing:-.07em;font-weight:600;margin:0 0 28px;color:var(--t1);opacity:0;transform:translateY(26px);animation:land-title .9s .16s cubic-bezier(.16,.78,.25,1) forwards}.landing-title em{display:block;color:var(--t3);font-style:normal;font-weight:450}.landing-lede{max-width:560px;font-size:clamp(1rem,1.5vw,1.08rem);line-height:1.75;color:var(--t2);opacity:0;transform:translateY(16px);animation:land-in .75s .34s cubic-bezier(.2,.75,.25,1) forwards}
.landing-access{max-width:650px;margin-top:40px;border-top:1px solid var(--border-h);border-bottom:1px solid var(--border-h);padding:16px 0 8px;opacity:0;transform:translateY(14px);animation:land-in .7s .46s cubic-bezier(.2,.75,.25,1) forwards}.landing-access-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.landing-url{display:flex;align-items:center;font-family:'JetBrains Mono',monospace;font-size:.82rem;color:var(--t3);padding:14px 0 18px;white-space:nowrap;overflow:auto}.landing-url strong{color:var(--t1);font-weight:500}
.landing-step{position:relative;display:grid;grid-template-columns:38px 1fr;gap:8px;padding:14px 0;border-bottom:1px solid var(--border);transition:padding-left .24s cubic-bezier(.2,.75,.25,1),color .2s ease}.landing-step:last-child{border-bottom:0}.landing-step::after{content:'';position:absolute;left:0;right:0;bottom:-1px;height:1px;background:var(--forest);transform:scaleX(0);transform-origin:left;transition:transform .32s cubic-bezier(.2,.75,.25,1);opacity:.55}.landing-step:hover{padding-left:8px}.landing-step:hover::after{transform:scaleX(1)}.landing-step>span{font-family:'JetBrains Mono',monospace;font-size:.66rem;color:var(--forest);padding-top:3px}.landing-step p{font-size:.84rem;color:var(--t2);line-height:1.5}.landing-footnote{font-size:.72rem;color:var(--t4);margin-top:18px;opacity:0;animation:land-in .7s .56s cubic-bezier(.2,.75,.25,1) forwards}
.landing-stage{position:relative;min-height:520px;display:flex;align-items:center;justify-content:center;perspective:1200px;opacity:0;animation:land-stage-in 1s .22s cubic-bezier(.16,.78,.25,1) forwards}.landing-stage::before{content:'';position:absolute;width:72%;height:70%;border:1px solid rgba(191,198,196,.08);border-radius:32px;transform:rotate(-7deg);animation:land-frame 9s ease-in-out infinite}.landing-stage::after{content:'';position:absolute;width:62%;height:62%;border:1px solid rgba(111,143,114,.12);border-radius:28px;transform:rotate(7deg);animation:land-frame-rev 11s ease-in-out infinite}
.landing-note-card{position:relative;width:min(430px,88%);padding:18px;border-radius:20px;border:1px solid rgba(191,198,196,.12);background:linear-gradient(180deg,rgba(28,28,25,.92),rgba(16,16,14,.96));box-shadow:0 30px 80px rgba(0,0,0,.35),0 0 0 1px rgba(255,255,255,.015) inset;transform:rotateX(4deg) rotateY(-5deg) translate3d(calc(var(--mx,0)*.35),calc(var(--my,0)*.35),0);transition:transform .55s cubic-bezier(.2,.65,.3,1),border-color .25s ease,box-shadow .35s ease;animation:land-card-float 8s ease-in-out infinite}.landing-note-card:hover{border-color:rgba(111,143,114,.24);box-shadow:0 38px 96px rgba(0,0,0,.4),0 0 60px rgba(111,143,114,.06)}
.note-window-head{display:flex;align-items:center;justify-content:space-between;padding-bottom:14px;border-bottom:1px solid var(--border);font-size:.68rem;color:var(--t3)}.note-dots{display:flex;gap:5px}.note-dots i{width:6px;height:6px;border-radius:50%;background:var(--s5)}.note-dots i:first-child{background:var(--red)}.note-dots i:nth-child(2){background:var(--amber)}.note-dots i:nth-child(3){background:var(--forest)}.note-body{padding:22px 4px 12px;font-family:'JetBrains Mono',monospace;font-size:.79rem;line-height:1.8;color:var(--t2)}.note-line{display:block;opacity:0;transform:translateX(-8px);animation:land-line-in .5s forwards}.note-line:nth-child(1){animation-delay:.7s}.note-line:nth-child(2){animation-delay:.78s}.note-line:nth-child(3){animation-delay:.86s}.note-line:nth-child(4){animation-delay:.94s}.note-line:nth-child(5){animation-delay:1.02s}.note-line:nth-child(6){animation-delay:1.1s}.note-caret{display:inline-block;width:7px;height:15px;margin-left:3px;background:var(--forest);vertical-align:-2px;animation:land-caret 1.05s steps(1,end) infinite}.note-highlight{color:var(--forest)}.note-dim{color:var(--t4)}
.landing-chip{position:absolute;display:flex;align-items:center;gap:8px;padding:9px 12px;border:1px solid var(--border-h);border-radius:12px;background:rgba(15,15,14,.82);backdrop-filter:blur(16px);font-size:.68rem;color:var(--t2);box-shadow:var(--sh2);animation:land-chip 6s ease-in-out infinite}.landing-chip strong{color:var(--t1);font-weight:600}.landing-chip-a{right:-2%;top:12%;animation-delay:-1.5s}.landing-chip-b{left:0;bottom:14%;animation-delay:-3.5s}.landing-chip-dot{width:6px;height:6px;border-radius:50%;background:var(--forest);box-shadow:0 0 10px rgba(111,143,114,.45)}
.landing-foot{display:flex;align-items:center;gap:8px;margin-top:40px;color:var(--t4);font-size:.68rem;letter-spacing:.03em;opacity:0;animation:land-in .7s .68s cubic-bezier(.2,.75,.25,1) forwards}.landing-foot-dot{width:6px;height:6px;border-radius:50%;background:var(--forest);box-shadow:0 0 0 4px var(--forest-a),0 0 16px rgba(111,143,114,.2);animation:land-status 2.8s ease-in-out infinite}
@keyframes land-in{to{opacity:1;transform:none}}@keyframes land-title{from{opacity:0;transform:translateY(26px);filter:blur(6px)}to{opacity:1;transform:none;filter:blur(0)}}@keyframes land-stage-in{from{opacity:0;transform:translateY(28px) scale(.985)}to{opacity:1;transform:none}}@keyframes land-line-in{to{opacity:1;transform:none}}@keyframes land-caret{0%,44%{opacity:1}45%,100%{opacity:0}}@keyframes land-breathe{0%,100%{transform:translate3d(var(--mx,0),var(--my,0),0) scale(.98);opacity:.75}50%{transform:translate3d(var(--mx,0),var(--my,0),0) scale(1.04);opacity:1}}@keyframes land-card-float{0%,100%{margin-top:0}50%{margin-top:-8px}}@keyframes land-frame{0%,100%{transform:rotate(-7deg)}50%{transform:rotate(-4deg) translate3d(4px,-6px,0)}}@keyframes land-frame-rev{0%,100%{transform:rotate(7deg)}50%{transform:rotate(4deg) translate3d(-5px,7px,0)}}@keyframes land-chip{0%,100%{transform:translateY(0)}50%{transform:translateY(-7px)}}@keyframes land-status{0%,100%{opacity:.6;transform:scale(.92)}50%{opacity:1;transform:scale(1.08)}}
@media(max-width:900px){.landing-panel{grid-template-columns:1fr;gap:28px;padding-top:100px}.landing-stage{min-height:420px;order:2}}
@media(max-width:640px){.landing-shell{padding:0 18px}.landing-panel{padding:88px 0 44px}.landing-title{font-size:clamp(3rem,13vw,4.6rem)}.landing-stage{min-height:360px}.landing-note-card{width:96%}.landing-chip-a{right:-3%;top:7%}.landing-chip-b{left:-2%;bottom:8%}.note-body{font-size:.7rem}.landing-url{font-size:.74rem}}@media(prefers-reduced-motion:reduce){.landing-shell *,.landing-shell::before,.landing-shell::after{animation:none!important;transition:none!important}.landing-title,.landing-copy-wrap,.landing-access,.landing-footnote,.landing-foot,.landing-stage{opacity:1!important;transform:none!important;filter:none!important}}
`}
