export function getRefinedCSS(){return `
/* PasteNote UI Revamp — admin + visitor + landing */
:root{--ui-ease:cubic-bezier(.22,.61,.36,1);--ui-fast:150ms;--ui-base:240ms;--ui-slow:520ms}
*{-webkit-tap-highlight-color:transparent}
html{scroll-behavior:smooth}
body{background:var(--s1);background-image:radial-gradient(circle at 50% -18%,rgba(111,143,114,.06),transparent 36%)}
.hdr{height:60px;background:color-mix(in srgb,var(--s1) 86%,transparent);border-bottom:1px solid color-mix(in srgb,var(--border-h) 50%,transparent);transition:background var(--ui-base) var(--ui-ease),border-color var(--ui-base) var(--ui-ease)}
.hdr-in{max-width:1180px;padding:0 28px}.brand-name{font-size:1rem;letter-spacing:-.035em}.theme-btn{background:transparent;color:var(--t3);border:1px solid var(--border);transition:background var(--ui-fast) var(--ui-ease),color var(--ui-fast) var(--ui-ease),border-color var(--ui-fast) var(--ui-ease),transform 120ms var(--ui-ease)}.theme-btn:hover{background:var(--s3);color:var(--t1);border-color:var(--border-h);transform:none;box-shadow:none}.theme-btn:active{transform:scale(.96)}
.nav-pills{background:transparent;border:0;padding:0;gap:4px}.nav-pill{padding:7px 13px;border-radius:8px;color:var(--t3);transition:background var(--ui-fast) var(--ui-ease),color var(--ui-fast) var(--ui-ease)}.nav-pill:hover{background:var(--s3);color:var(--t1)}.nav-pill.active{background:var(--s3);color:var(--t1);box-shadow:none}
.page{max-width:1160px;padding:92px 28px 56px}
.card{border-radius:14px;background:color-mix(in srgb,var(--s2) 96%,transparent);box-shadow:0 1px 1px rgba(0,0,0,.08);transition:border-color var(--ui-base) var(--ui-ease),background var(--ui-base) var(--ui-ease),box-shadow var(--ui-base) var(--ui-ease),transform var(--ui-base) var(--ui-ease)}.card:hover{border-color:var(--border-h);box-shadow:0 12px 34px rgba(0,0,0,.12)}.card-icon,.card:hover .card-icon{transform:none;transition:background var(--ui-base) var(--ui-ease),color var(--ui-base) var(--ui-ease)}
.btn{transition:background var(--ui-fast) var(--ui-ease),border-color var(--ui-fast) var(--ui-ease),color var(--ui-fast) var(--ui-ease),transform 100ms var(--ui-ease),opacity var(--ui-fast) var(--ui-ease)}.btn::after{display:none}.btn:hover{box-shadow:none}.btn:active{transform:translateY(1px) scale(.985)}
.inp{transition:border-color var(--ui-fast) var(--ui-ease),background var(--ui-fast) var(--ui-ease),box-shadow var(--ui-fast) var(--ui-ease)}
.landing .page-center{min-height:100vh;padding:88px 24px 56px}.land-card{max-width:680px;text-align:left;padding:10px 0 0}.land-title{margin-bottom:22px}.land-title .brand-name{font-size:.76rem;letter-spacing:.18em;text-transform:uppercase;color:var(--t3)}.land-card:before{content:'PRIVATE NOTE SPACE';display:block;font-size:.64rem;font-weight:700;letter-spacing:.16em;color:var(--forest);margin-bottom:18px}.info-box{margin:38px 0 0;padding:0;background:transparent;border:0;border-top:1px solid var(--border-h);border-radius:0}.info-label{margin:0;padding:17px 0 12px;border:0;color:var(--t3);letter-spacing:.14em;font-size:.64rem}.steps li{padding:15px 0 15px 42px;margin:0;border-bottom:1px solid var(--border);transition:padding-left var(--ui-base) var(--ui-ease),background var(--ui-base) var(--ui-ease)}.steps li:hover{padding-left:48px;background:linear-gradient(90deg,var(--forest-a),transparent 55%)}.steps li::before{left:0;top:16px;background:transparent;border:1px solid var(--border-h);color:var(--forest);width:22px;height:22px}.steps code{background:transparent;padding:0}.land-muted{margin-top:18px}.landing .page-center:after{content:'Hover a step to explore';position:fixed;bottom:22px;left:50%;transform:translateX(-50%);font-size:.65rem;letter-spacing:.06em;color:var(--t4);opacity:.75;animation:landingHint 3s var(--ui-ease) infinite}.landing .land-card{animation:uiIn .65s var(--ui-ease) both}.landing .steps li{animation:uiIn .5s var(--ui-ease) both}.landing .steps li:nth-child(1){animation-delay:.08s}.landing .steps li:nth-child(2){animation-delay:.14s}.landing .steps li:nth-child(3){animation-delay:.20s}
@keyframes uiIn{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:none}}@keyframes landingHint{0%,100%{opacity:.35}50%{opacity:.85}}
.admin-dash .page{padding-top:88px}.admin-dash .stats{grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:18px}.admin-dash .stat{position:relative;padding:16px 18px;border-radius:12px;background:transparent;box-shadow:none;transition:background var(--ui-base) var(--ui-ease),border-color var(--ui-base) var(--ui-ease),transform var(--ui-base) var(--ui-ease)}.admin-dash .stat:hover{transform:translateY(-2px);background:var(--s2);box-shadow:0 10px 24px rgba(0,0,0,.12)}.admin-dash .stat:nth-child(1),.admin-dash .stat:nth-child(2),.admin-dash .stat:nth-child(3){border-left:1px solid var(--border-h)}.admin-dash .stat-num{font-size:1.9rem;letter-spacing:-.04em}.admin-dash .stat-name{font-size:.63rem}.admin-dash .card-header{padding:14px 18px}.admin-dash .card-body{padding:10px 18px 16px}.admin-dash .tbl{min-width:720px;border-spacing:0 4px}.admin-dash .tbl thead th{background:transparent;border:0;padding:8px 12px;color:var(--t4);font-size:.61rem}.admin-dash .tbl tbody tr{background:transparent;transition:background var(--ui-fast) var(--ui-ease),transform var(--ui-fast) var(--ui-ease)}.admin-dash .tbl tbody tr:hover{background:var(--s3);transform:translateX(2px)}.admin-dash .tbl tbody td{border-top:1px solid transparent;border-bottom:1px solid transparent;padding:12px}.admin-dash .tbl tbody tr:hover td{border-color:var(--border)}.admin-dash .tbl-link,.admin-dash .tbl tbody td:nth-child(3){font-family:'JetBrains Mono',monospace;font-size:.74rem;color:var(--forest)}.admin-dash .badge{padding:3px 7px;font-size:.58rem;letter-spacing:.06em}.admin-dash .field-actions{position:sticky;bottom:0;padding:14px 0;background:linear-gradient(transparent,var(--s2) 25%)}.admin-dash .tab{animation:uiTab .25s var(--ui-ease) both}@keyframes uiTab{from{opacity:0;transform:translateY(5px)}to{opacity:1;transform:none}}
.unlocked .page{max-width:1040px}.unlocked .card{border-radius:16px}.unlocked .note-text{font-size:1rem;line-height:1.85;max-width:780px}.unlocked .card-header{padding:15px 18px}.unlocked .card-body{padding:18px}.unlocked .mail-list{gap:0}.unlocked .mail-item{background:transparent;border-bottom:1px solid var(--border);transition:background var(--ui-fast) var(--ui-ease),border-color var(--ui-fast) var(--ui-ease)}.unlocked .mail-item:last-child{border-bottom:0}.unlocked .mail-row{min-height:68px;padding:13px 16px;transition:background var(--ui-fast) var(--ui-ease),padding-left var(--ui-fast) var(--ui-ease)}.unlocked .mail-row:hover{background:var(--s3);padding-left:20px}.unlocked .mail-row.unread{background:transparent}.unlocked .mail-row.unread .mail-sender,.unlocked .mail-row.unread .mail-subj{font-weight:700}.unlocked .mail-avatar{width:34px;height:34px;box-shadow:inset 0 0 0 1px rgba(255,255,255,.08)}.unlocked .mail-right{opacity:.9;transition:opacity var(--ui-fast) var(--ui-ease),transform var(--ui-fast) var(--ui-ease)}.unlocked .mail-row:hover .mail-right{opacity:1;transform:translateX(-2px)}.unlocked .otp-code{background:var(--s3);border:1px solid var(--border);color:var(--amber);padding:5px 9px;transition:background var(--ui-fast) var(--ui-ease),border-color var(--ui-fast) var(--ui-ease),color var(--ui-fast) var(--ui-ease)}.unlocked .otp-code:hover{transform:none;background:var(--amber-a);border-color:var(--amber);color:var(--amber-h)}.unlocked .copy-btn{border-color:var(--border);transition:background var(--ui-fast) var(--ui-ease),color var(--ui-fast) var(--ui-ease)}.unlocked .mail-item.expanded{margin:4px 0;background:var(--s3);border:1px solid var(--border-h);box-shadow:0 10px 28px rgba(0,0,0,.12)}.unlocked .mail-detail{animation:mailOpen .28s var(--ui-ease) both;padding-top:2px}.unlocked .mail-detail-meta{animation:metaOpen .22s var(--ui-ease) both}.unlocked .inbox-empty{padding:54px 24px}.unlocked .cd-badge{animation:none}.unlocked .status{border:1px solid var(--border)}
@keyframes mailOpen{from{opacity:0;transform:translateY(-5px);clip-path:inset(0 0 8% 0)}to{opacity:1;transform:none;clip-path:inset(0)}}@keyframes metaOpen{from{opacity:0;transform:translateY(-3px)}to{opacity:1;transform:none}}
.locked .lock-card,.admin-login .alogin-card{box-shadow:none;animation:uiIn .55s var(--ui-ease) both}.lock-card:hover,.alogin-card:hover{box-shadow:0 14px 36px rgba(0,0,0,.14)}
.fade-up{animation:uiIn .5s var(--ui-ease) both}.fade-up-d1{animation-delay:70ms}.fade-up-d2{animation-delay:120ms}.fade-up-d3{animation-delay:170ms}
@media(max-width:720px){.hdr-in{padding:0 16px}.page{padding-left:16px;padding-right:16px}.admin-dash .stats{grid-template-columns:1fr;gap:6px}.admin-dash .stat{flex-direction:row;align-items:center;justify-content:space-between}.landing .page-center{padding-left:18px;padding-right:18px}.land-card{width:100%}.unlocked .card-header{align-items:flex-start}.unlocked .mail-row{padding-left:12px;padding-right:12px}.unlocked .mail-row:hover{padding-left:14px}.unlocked .mail-right{display:none}}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:1ms!important;transition-duration:1ms!important;scroll-behavior:auto!important}}
`;}
